name: Deploy CloudFormation Stack
description: Deploy CloudFormation S3 Bucket Stack

on:
  workflow_dispatch:
  push:
    branches:
      - feature/**
      - bug/**
    paths:
      - 'templates/**'
      - .github/workflows/ci.yaml


permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  setup-environment:
    name: Setup Environment Variables
    runs-on: ubuntu-latest
    environment: devl
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
      aws-region: ${{ steps.set-env.outputs.aws-region }}
      aws-account-id: ${{ steps.set-env.outputs.aws-account-id }}
      oidc-role-name: ${{ steps.set-env.outputs.oidc-role-name }}
      s3-bucket: ${{ steps.set-env.outputs.s3-bucket }}
    steps:
      - name: Read environment-specific variables
        id: set-env
        run: |
          echo "environment=${{ vars.AWS_ENVIRONMENT }}" >> $GITHUB_OUTPUT
          echo "aws-region=${{ vars.AWS_REGION }}" >> $GITHUB_OUTPUT
          echo "aws-account-id=${{ vars.AWS_ACCOUNT_ID }}" >> $GITHUB_OUTPUT
          echo "oidc-role-name=${{ vars.AWS_OIDC_ROLE_NAME }}" >> $GITHUB_OUTPUT
          echo "s3-bucket=${{ vars.CFN_NESTED_TEMPLATES_S3_BUCKET_NAME }}" >> $GITHUB_OUTPUT

          echo "## Environment Configuration" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Environment | ${{ vars.AWS_ENVIRONMENT }} |" >> $GITHUB_STEP_SUMMARY
          echo "| AWS Region | ${{ vars.AWS_REGION }} |" >> $GITHUB_STEP_SUMMARY
          echo "| AWS Account ID | ${{ vars.AWS_ACCOUNT_ID }} |" >> $GITHUB_STEP_SUMMARY
          echo "| AWS OIDC Role Name | ${{ vars.AWS_OIDC_ROLE_NAME }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Nested Templates S3 Bucket Name | ${{ vars.CFN_NESTED_TEMPLATES_S3_BUCKET_NAME }} |" >> $GITHUB_STEP_SUMMARY

  deploy-s3-bucket-stack:
    name: Deploy S3 Bucket Stack
    needs: setup-environment
    uses: subhamay-bhattacharyya-gha/cloudformation-deploy-wf/.github/workflows/cfn-deploy.yaml@v1.1.0
    with:
      environment: ${{ needs.setup-environment.outputs.environment }}
      concurrency-group: ${{ github.workflow }}-${{ needs.setup-environment.outputs.environment }}
      aws-region: ${{ needs.setup-environment.outputs.aws-region }}
      aws-account-id: ${{ needs.setup-environment.outputs.aws-account-id }}
      oidc-role-name: ${{ vars.AWS_OIDC_ROLE_NAME }}
      cfn-templates-s3-bucket: ${{ vars.CFN_NESTED_TEMPLATES_S3_BUCKET_NAME }}
      stack-name: s3-bucket-stack
      parameters-file: templates/parameters.json
      template-file: templates/s3-bucket.yaml